codecov:
  require_ci_to_pass: true
  disable_default_path_fixes: false

fixes:
  - "/src/main/java/com/neven/ticTacToeGame/::"

coverage:
  precision: 1
  round: down
  range: "65...70"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false