package com.neven.ticTacToeGame;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Class {@code TicTacToeGameApplication} it is a main class of application.
 * <br>In this class uses {@code @SpringBootApplication} annotation.
 * <br>Class was autogenerated by IntelliJ Idea.
 *
 * @see <a href="https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/SpringBootApplication.html">Annotation Type SpringBootApplication</a>
 */
@SpringBootApplication
public class TicTacToeGameApplication {

    /**
     * @param args java command line arguments.
     * @see <a href="https://www.journaldev.com/12552/public-static-void-main-string-args-java-main-method">Java main method</a>
     */
    public static void main(String[] args) {
        SpringApplication.run(TicTacToeGameApplication.class, args);
    }
}